Vagrant.configure("2") do |config|
    config.vm.box = "gusztavvargadr/windows-server"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    config.vm.network "public_network", ip: "192.168.1.10", netmask: "255.255.255.0"
    config.vm.provision "shell", inline: <<-SHELL
      netsh interface ip set address "Ethernet" static 192.168.1.10 255.255.255.0 192.168.1.1
      netsh interface ip set dns "Ethernet" static 192.168.1.1
    SHELL
    config.vm.synced_folder ".", "/vagrant", disabled: true
  end